INSERT INTO users (name, age) VALUES ("Abe", 5);
INSERT INTO users (name, age) VALUES ("Barry", 7);
INSERT INTO users (name, age) VALUES ("Charlie", 3);
INSERT INTO users (name, age) VALUES ("Dave", 41);
INSERT INTO users (name, age) VALUES ("Evelyn", 17);
INSERT INTO users (name, age) VALUES ("Frank", 67);
INSERT INTO users (name, age) VALUES ("George", 35);
INSERT INTO users (name, age) VALUES ("Harold", 18);
INSERT INTO users (name, age) VALUES ("Ivan", 45);
INSERT INTO users (name, age) VALUES ("Jeff", 42);
INSERT INTO users (name, age) VALUES ("Kyle", 25);
INSERT INTO users (name, age) VALUES ("Larry", 27);
INSERT INTO users (name, age) VALUES ("Monica", 29);
INSERT INTO users (name, age) VALUES ("Neil", 38);
INSERT INTO users (name, age) VALUES ("Oliver", 56);
INSERT INTO users (name, age) VALUES ("Percy", 78);
INSERT INTO users (name, age) VALUES ("Ryan", 51);
INSERT INTO users (name, age) VALUES ("Sarah", 60);
INSERT INTO users (name, age) VALUES ("Tom", 62);
INSERT INTO users (name, age) VALUES ("Victor", 32);


INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("good project", "healthcare", 100, "JAN 12, 2030", "JAN 02, 2031");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("fun project", "art", 1000, "FEB 15, 2022", "FEB 02, 2032");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("selfish", "business", 1500, "DEC 23, 2023", "MAR 02, 2033");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("tacos", "sports", 23456, "DEC 22, 2023", "JAN 02, 2024");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("clothing", "kids", 5000234, "OCT 16, 2024", "APR 02, 2025");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("smarty", "learning", 34001, "NOV 05, 2026", "MAY 02, 2027");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("safety", "kids", 1, "JAN 08, 2035", "JUN 02, 2036");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("creative", "art", 999999, "MAR 17, 2021", "JUL 02, 2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("money", "business", 98743, "APR 29, 2035", "AUG 02, 2036");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("worthwhile", "healthcare", 123, "JUL 28, 2030", "NOV 02, 2032");

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1023, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (333, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (44, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (13450, 7, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (133333333, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (177, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (19, 9, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 5, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 8, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3456, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (77, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2540, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 13, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (23, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (101, 15, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90, 16, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1500, 17, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (17800, 19, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (77, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (76, 20, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (80, 15, 9);
